name: Update DOI and Citation
on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-citation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Wait for Zenodo processing
        run: sleep 300

      - name: Ensure jq is installed
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract Zenodo DOI from release comments
        id: extract_doi
        run: |
          echo "→ Fetching comments from ${{ github.event.release.comments_url }}"
          COMMENTS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.event.release.comments_url }}")

          # Pull the first DOI-like string out of any comment body
          DOI=$(echo "$COMMENTS" \
            | jq -r '.[].body' \
            | grep -Eo '10\.[0-9]+\/zenodo\.[0-9]+' \
            | head -n1)

          if [ -z "$DOI" ]; then
            echo "::error::Could not find Zenodo DOI in release comments!"
            exit 1
          fi

          echo "Found DOI: $DOI"
          echo "doi=$DOI" >> $GITHUB_OUTPUT

      - name: Update CITATION.cff
        run: |
          TAG=${{ github.event.release.tag_name }}
          TODAY=$(date +%F)

          sed -i "s/^version:.*/version: $TAG/" CITATION.cff
          sed -i "s|^date-released:.*|date-released: $TODAY|" CITATION.cff

          if grep -q '^doi:' CITATION.cff; then
            sed -i "s|^doi:.*|doi: ${{ steps.extract_doi.outputs.doi }}|" CITATION.cff
          else
            sed -i "/^date-released:/a doi: ${{ steps.extract_doi.outputs.doi }}" CITATION.cff
          fi

      - name: Commit & push
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add CITATION.cff
          git commit -m "chore: bump citation for $TAG" || echo "No changes"
          git push origin main
