name: Update DOI and Citation
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  update-citation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait for Zenodo processing
        run: sleep 300
      - name: Update CITATION.cff
        run: |
          sed -i "s/^version:.*/version: ${{ github.event.release.tag_name }}/" CITATION.cff
          sed -i "s/^date-released:.*/date-released: $(date +%Y-%m-%d)/" CITATION.cff
      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add CITATION.cff
          git commit -m "Update citation info for ${{ github.event.release.tag_name }}" || exit 0
          git push
