name: Update DOI and Citation
on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write   # needed so the GITHUB_TOKEN can push

jobs:
  update-citation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Wait for Zenodo processing
        run: sleep 300

      - name: Update CITATION.cff
        run: |
          sed -i "s/^version:.*/version: ${{ github.event.release.tag_name }}/" CITATION.cff
          sed -i "s|^date-released:.*|date-released: $(date +%Y-%m-%d)|" CITATION.cff

      - name: Commit & push changes
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add CITATION.cff
          git commit -m "Update citation info for ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin main
